#!/bin/bash

CONFIG_DIR=/etc/config.d/network
CONFIG_DIR=/etc/systemd/network
LNET_FUNCTIONS=/var/lib/lunar/functions/lnet
LNET_BOOTSTRAP=$FUNCTIONS/bootstrap

. /etc/lunar/config
[ -n "$BOOTSTRAP" ] && . $BOOTSTRAP

. $LNET_BOOTSTRAP

export IFS="$TAB_ENTER_IFS"

DIALOG="dialog
--backtitle
Lunar Network Management Utility
--stdout"

if [  "${BASH_SOURCE[0]}" == "$0" ]
then
    main_menu
fi
