#!/bin/bash

CONFIG_DIR=/etc/config.d/network
CONFIG_DIR=/etc/systemd/network

# Check whether we're running in dev or release mode
if [ -d $(basename -- $0)/../lib/lnet ]
then
    LNET_FUNCTIONS=$(cd $(basename $0/../lib/lnet) && pwd)
else
    LNET_FUNCTIONS=/var/lib/lunar/functions/lnet
fi

LNET_BOOTSTRAP=$LNET_FUNCTIONS/bootstrap

. /etc/lunar/config
[ -n "$BOOTSTRAP" ] && . $BOOTSTRAP

. $LNET_BOOTSTRAP

export IFS="$TAB_ENTER_IFS"

DIALOG="dialog
--backtitle
Lunar Network Management Utility
--stdout"

if [  "${BASH_SOURCE[0]}" == "$0" ]
then
    main_menu
fi
